import esbuild from "esbuild";
import fs from "fs/promises";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = "dist";

async function copyStaticFiles() {
	await fs.mkdir(outdir, { recursive: true });
	await Promise.all([
		fs.copyFile("manifest.json", path.join(outdir, "manifest.json")),
		fs.copyFile("styles.css", path.join(outdir, "styles.css")),
	]);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outdir, "main.js"),
});

if (prod) {
	await context.rebuild();
	await copyStaticFiles();
	process.exit(0);
} else {
	await copyStaticFiles();
	await context.watch();
}
